### ISSUE TITLE
Possibility to specify element-web address/location in matrix.to …

### ISSUE THREAD

**Issue by fooness** [matrix-org/matrix.to#169] opened 2020-11-26 19:13 UTC
It seems there’s currently no way to open any `matrix.to` link in your self-hosted Element-Web client. Why?

**Comment by aaronraimist** [comment] 2020-11-26 21:05
Duplicate of https://github.com/matrix-org/matrix.to/issues/23

**Closed** 2020-11-26 21:07 UTC
