### ISSUE TITLE
words must not be broken by letters

### ISSUE THREAD

**Issue by 532910** [matrix-org/matrix.to#134] opened 2020-09-21 18:29 UTC
![image](https://user-images.githubusercontent.com/14617699/93806205-7bee8080-fc51-11ea-8374-b50bb1185f55.png)

FF 80.0.1 (64-bit), monitor size 1600x1200

**Comment by t3chguy** [comment] 2020-09-21 18:33
Duplicate of #112

**Closed** 2020-09-21 18:33 UTC
