### ISSUE TITLE
Doesn't try to use installed desktop client on Chromium browsers on macOS

### ISSUE THREAD

**Issue by directhex** [matrix-org/matrix.to#244] opened 2021-11-19 17:58 UTC
**Describe the bug**
I'm running macOS 12.0.1, and use Edge as my daily driver. I was provided a matrix.to link, picked a client (Element), opted to download it rather than use via the web, and did all the required signup to have the client working. When I tried the matrix.to link again, clicking continue made no effort at all to actually invoke my local app, in either Edge or Chrome - however, with Safari, it asked to open in the app. I also tried Edge on Ubuntu, which called xdg-open as expected. The Mac+Chromium case is specifically the broken one

**To Reproduce**
1. Install Chrome or Edge or something on a Mac
2. Install Element desktop client
3. Click https://matrix.to/#/#matrix-curious:matrix.org and hit continue on Element

**Expected behavior**
Something approximating the Safari behaviour

**Screenshots**
<img width="686" alt="Screen Shot 2021-11-19 at 12 56 43 PM" src="https://user-images.githubusercontent.com/308992/142669359-78c759ba-7bbe-4803-84f7-6b36f81228b9.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Browser: Edge 95.0.1020.53, Chrome 96.0.4664.55
 - Version: Element version: 1.9.4

**Comment by t3chguy** [comment] 2021-11-19 18:02
Duplicate of https://github.com/matrix-org/matrix.to/issues/230

**Closed by t3chguy** 2021-11-19 18:02 UTC
