### ISSUE TITLE
Input box has outline

### ISSUE THREAD

**Issue by resynth1943** [matrix-org/matrix.to#157] opened 2020-09-30 00:38 UTC
**Describe the bug**

When selected, the input has an `outline`. This is ugly, and could be replaced with a `border`.

**To Reproduce**
1. Go to matrix.to
2. Click on the input box
3. Explosion

**Expected behavior**

No `outline`. It doesn't have a `border-radius`, so it's always going to look ugly. We could remove it, but replace it with a `border` for accessibility.

**Screenshots**

![Screenshot_20200930-013135](https://user-images.githubusercontent.com/49915996/94630364-0c157100-02b5-11eb-807e-2bc1612e6a76.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 11
 - Browser: Bromite / Vanadium (Chromium)
 - Version: N/A

**Additional context**

N / A

**Comment by jryans** [comment] 2020-09-30 09:25
Duplicate of https://github.com/matrix-org/matrix.to/issues/120

**Closed by jryans** 2020-09-30 09:25 UTC

**Comment by resynth1943** [comment] 2020-09-30 10:36
Thankie
