### ISSUE TITLE
Fonts not loading

### ISSUE THREAD

**Issue by resynth1943** [matrix-org/matrix.to#143] opened 2020-09-23 13:40 UTC
**Describe the bug**

On this computer, the fonts aren't being requested. The entire site is in Serif (it looks horrible.)

**To Reproduce**
1. Go to matrix.to
2. "My eyes, my eyes!"

**Expected behavior**

The website loads a good font, instead of relying on ugly browser defaults.

**Screenshots**

![image](https://user-images.githubusercontent.com/49915996/94020152-81131300-fdaa-11ea-8ac1-a3c1e0e12318.png)

**Desktop (please complete the following information):**
 - OS: Apologetically, it's Windows 10 (not mine.)
 - Browser: Firefox
 - Version: 72.0.2 (32-bit)

**Additional context**

I've checked the Developer Tools, and *no font files are being loaded.*

**Comment by JorikSchellekens** [comment] 2020-09-23 14:51
Duplicate of https://github.com/matrix-org/matrix.to/issues/121. Fixed but not deployed yet

**Closed by JorikSchellekens** 2020-09-23 14:51 UTC

**Comment by resynth1943** [comment] 2020-09-24 11:49
> not deployed yet

Why?
