### ISSUE TITLE
URL previews have limited information

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.to#41] opened 2018-06-16 16:36 UTC
![image](https://user-images.githubusercontent.com/1190097/41500559-0cc123da-7151-11e8-8154-f313f36475f4.png)

**Comment by t3chguy** [comment] 2018-06-16 16:46
Only way around this would be to get rid of the privacy and server-fetch data which is undesirable

**Comment by turt2live** [comment] 2018-06-16 16:50
True, matrix.to will never be able to make the riot side of this happy with that restriction. The preview could at least be helpful though: "matrix.to - join a room" or something that describes what the site does instead of just repeating the title.

**Comment by lampholder** [comment] 2018-06-18 13:39
I think this is pretty important - if we want to share links out of band then they need to not look... weird. 

Presumably we can inspect the URL to provide a little bit of context as to whether this is a permalink to a room, a message/event in a room, a user or a community. Perhaps something like:

- Permalink to a room on matrix.org
- Permalink to a message on matrix.org
- Permalink to Matrix user @tom:lant.uk
- Permalink to Matrix community +coolstuff:matrix.org

**Comment by turt2live** [comment] 2018-06-18 14:21
The problem is that URL previews generally use a meta header, and they can't be easily calculated given most parers grep the content without running javascript.

**Comment by t3chguy** [comment] 2018-06-18 15:55
So we can't do that because the server doesn't see the actual thing that's being linked to to generate the meta header

**Comment by t3chguy** [comment] 2018-06-18 15:55
(there isn't actually a server component to matrix.to)

**Comment by lampholder** [comment] 2018-06-26 12:32
Aaaaaaaand matrix.to page content is generated clientside. Boo!

Presumably we _could_ make a server-generated matrix.to server that stuffs a more useful summary into the meta header?

**Comment by lampholder** [comment] 2018-06-26 12:33
By which I mean something which honours the exact same URL scheme but generates the dynamic bits serverside rather than clientside

**Comment by JorikSchellekens** [comment] 2020-09-21 15:52
I'm going to add open graph details to matrix.to that give a little more info about what a matrix.to link is. Unfortunately it seems there is no way to maintain privacy and provide better link previews.

**Comment by t3chguy** [comment] 2021-07-15 13:20
Duplicate of https://github.com/matrix-org/matrix.to/issues/207

**Closed by t3chguy** 2021-07-15 13:20 UTC
Labels: matrix-two
